function I1 = instruction_example(type)
if strcmp(type,'char')
    I1 = [
        'Characters\n'...
        'There are two types:\n'...
        '1. 0-back task \n' ...
        '2. 1/2/3-back tasks \n' ...
        ' In 0-back task you will be asked to respond by clicking YES if the shown \n' ...
        'character is S, otherwise NO.\n'... 
        ' In the other type of tasks you need to compare and decide whether the shown\n'... 
        ' characters are same or not. \n' ...
        ' In both the tasks you will be having only two options\n' ...
        ' YES or NO \n' ...
        'Choose the one you think is correct \n'...        
        ];
elseif strcmp(type,'pos')
    I1 = [
        'Positions\n'...
        'There are two types:\n'...
        '1. 0-back task \n' ...
        '2. 1/2/3-back tasks \n' ...
        ' In 0-back task you will be asked to respond by clicking YES if the \n' ...
        ' highlited position is center, otherwise NO\n'...
        ' In the other type of tasks you need to compare and decide whether \n' ...
        ' the highlighted poositions are at same position or not. \n' ...
        ' In both the tasks you will be having only two options\n' ...
        ' YES or NO \n' ...
        'Choose the one you think is correct \n'...        
    ];
elseif strcmp(type,'bar')
    I1 = [
        'BAR Graphs\n'...
        'There are two types:\n'...
        '1. 0-back task \n' ...
        '2. 1/2/3-back tasks \n' ...
        ' In 0-back task you will be asked to respond by clicking YES if the specified month is\n'...
        'greater than 50cm, otherwise NO \n' ...
        ' In the other type of tasks you need to compare and decide whether the specified month is\n'...
        'greater than the previously shown month n-slides ago or not. \n' ...
        ' In both the tasks you will be having only two options\n' ...
        ' YES or NO \n' ...
        'if current month rainfall is greater than the rainfall of the month shown n-slides ago\n'...
        'then YES, otherwise NO \n'...
        'Choose the one you think is correct \n'...
        ];
elseif strcmp(type,'pie')
    I1 = [
        'PIE Charts\n'...
        'There are two types:\n'...
        '1. 0-back task \n' ...
        '2. 1/2/3-back tasks \n' ...
        ' In 0-back task you will be asked to respond by clicking YES if the specified month\n'...
        'rainfall is the highest among all, otherwise NO \n' ...
        ' In the other type of tasks you need to compare and decide whether the specified month \n'...
        'is greater than the previously\n'...
        'shown month n-slides agoor not. \n' ...
        ' In both the tasks you will be having only two options\n' ...
        ' YES or NO \n' ...
        'if current month rainfall is greater than the rainfall of the month shown n-slides ago\n'...
        'then YES, otherwise NO \n'...
        'Choose the one you think is correct \n'...
        ];
end
